### PR TITLE
Assembly updates; buildable with lastest maven

### PR DESCRIPTION
**Pull request by jdillon**
Drops layered apache-maven assembly, reverts back to original distribution specific to shell.
Rips out the sonatype sisu-assembly muck completely.
Updates version to 1.2.0-SNAPSHOT
Bunch of tidy.

### CODE REVIEW

**Comment by cpfeiffer** [comment]
Thanks for porting this to newer Maven versions. I just tried to compile it with latest Maven 3.3.9, but it fails with 
`Found Banned Dependency: com.google.inject:guice:jar:no_aop:4.0`

If you force compilation with -Denforcer.skip=true, you will get a few compilation errors in the *TransferListener classes and MavenSystemImpl.

**Comment by jdillon** [comment]
@cpfeiffer I just tried with 3.3.9 (clean unzip from official distribution) and was not able to reproduce the failure you mention.  :-\

**Comment by cpfeiffer** [comment]
@jdillon Oh, wow. I've tried very hard to get it to work, which involved
- porting from org.sonatype.sisu to org.eclipse.sisu
- porting from PrintStreamLogger et al to slf4j Logger
- updating lots of [plugin] dependencies, and adding some
- porting gshell similarly (it explicitly mentions to not work on Maven 3.1+)
- fighting with "banned dependencies" (the no_aop thing)

In the end, I managed to compile both gshell and mvnsh, but guice (now at version 4.0) fails to wire all dependencies together. This is where I'm stuck so far.

And for you it *just works*?

I guess I'll try again with an empty ~/.m2 directory and see if this makes a difference.

Thanks for your quick answer!

**Comment by jdillon** [comment]
@cpfeiffer sounds like you are trying to upgrade the version of maven used by the shell, not make the current project buildable by latest maven.  This PR does the later not the former.

**Comment by cpfeiffer** [comment]
@jdillon Indeed, that's what I'm trying to do, thanks for the clarification. Would you be interested in that as well?

**Comment by jdillon** [comment]
@cpfeiffer if you open a PR I can try to take a look and see whats busted

**Comment by jdillon** [comment]
manually merged

**Comment by cpfeiffer** [comment]
Thank you, this is very kind! I'll make a pull request in a minute.
